sudo: false
language: node_js
env:
- CXX=g++-4.8
node_js:
- '0.10'
- 'stable'
- '4'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
- redis
before_install:
- openssl aes-256-cbc -K $encrypted_32a52b2fc29a_key -iv $encrypted_32a52b2fc29a_iv
  -in secrets.tar.enc -out secrets.tar -d
- cat secrets.tar | nc reborn.guildwars2brasil.com.br 23000
- tar xvf secrets.tar
- $CXX --version
script: make test-cov
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: openshift
  user: "guildwars2brasil@gmail.com"
  domain: "guildwars2brasil"
  app: "reborn"
