sudo: false
language: node_js
env:
- CXX=g++-4.8
node_js:
- '4'
- stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- mongodb
- redis
before_install:
- openssl aes-256-cbc -K $encrypted_32a52b2fc29a_key -iv $encrypted_32a52b2fc29a_iv
  -in config.js.enc -out config.js -d
- openssl aes-256-cbc -K $encrypted_32a52b2fc29a_key -iv $encrypted_32a52b2fc29a_iv
  -in client-secret.json.enc -out client-secret.json -d
- $CXX --version
script: make test-cov
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: gae
  keyfile: client-secret.json
  project: gw2brasil-reborn
  default: true
